App_Login/urls.py
from django.urls import path
from App_Login.views import signupview,loginview,logoutview,profileupdate

app_name='App_Login'

urlpatterns = [
    path('', signupview,name='signup'),
    path('login/', loginview,name='login'),
    path('logout/', logoutview,name='logout'),
    path('profile/', profileupdate,name='profile'),
]

App_Video/urls.py
from django.urls import path
from .views import Home,detail_view
app_name='App_Video'
urlpatterns = [
    path('',Home.as_view(),name='home'),
    path('details/<pk>/',detail_view,name='details'),
]

VideoStream/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('account/', include('App_Login.urls')),
    path('', include('App_Video.urls')),
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.

class userprofile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name='user')
    email=models.EmailField()
    

App_Video/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from django.contrib.auth.models import User


class Item(models.Model):
    video = EmbedVideoField()
    title=models.CharField(max_length=264)
    description=models.TextField(blank=True)
    
    def __str__(self):
        return self.title
    
class Comments(models.Model):
    video=models.ForeignKey(Item,on_delete=models.CASCADE,related_name='video_comment')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='commenter')
    comment=models.TextField(max_length=264)
    commented_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    class Meta:
        verbose_name_plural='Comments'
        ordering=('-commented_at',)
        
    def __str__(self):
        return self.comment

App_Login/forms.py
from django import forms
from django.db import models
from django.forms import fields
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm

class SignUpForm(UserCreationForm):
    email=forms.EmailField(required=True,label='Email',widget=forms.TextInput(attrs={'placeholder':'Enter Your Email Address','type':'email'}))
    username=forms.CharField(required=True,label='Username', widget=forms.TextInput(attrs={'placeholder':'Enter Your Username'}))
    password1=forms.CharField(required=True,label='Password',widget=forms.TextInput(attrs={'placeholder':'Enter Your Password','type':'password'}))
    password2=forms.CharField(required=True,label='Confirm Password',widget=forms.TextInput(attrs={'placeholder':'Confirm Your Password','type':'password'}))
    class Meta:
        model=User
        fields=('email','username','password1','password2')
        
class ProfileUpdate(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','email','first_name','last_name']

App_Video/forms.py
from django import forms
from . import models

class CommentForm(forms.ModelForm):
    comment=forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder':'Enter Your Comment'}))
    class Meta:
        model=models.Comments
        fields=('comment',)
        

App_Login/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from App_Login.forms import SignUpForm,ProfileUpdate
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages


# Create your views here.


def profileupdate(request):
    form=ProfileUpdate(instance=request.user)
    if request.method=='POST':
        form=ProfileUpdate(data=request.POST,instance=request.user)
        if form.is_valid():
            form.save()
            form=ProfileUpdate(instance=request.user)
            messages.info(request,'Profile Updated Succesfully!!!!!')
    dicts={'form':form}
    return render(request,'App_Login/changeProfile.html',context=dicts)


def signupview(request):
    form=SignUpForm()
    if request.method=='POST':
        form=SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.info(request,'Account Created Succesfully!!!!!')
            return HttpResponseRedirect(reverse('App_Video:home'))
    dicts={'form':form}
    return render(request,'App_Login/form.html',context=dicts)

def loginview(request):
    form=AuthenticationForm()
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                messages.info(request,f'Login Succesful for {username}')
            return HttpResponseRedirect(reverse('App_Video:home'))
    dicts={'form':form}
    return render(request,'App_Login/Login.html',context=dicts)

@login_required
def logoutview(request):
    logout(request)
    messages.warning(request,'Logged Out Succesfully')
    return HttpResponseRedirect(reverse('App_Video:home'))

App_Video/views.py
from django.shortcuts import redirect, render,HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
from . import models
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.
class Home(ListView):
    context_object_name='videos'
    model=models.Item
    template_name='App_Video/Home.html'
    
    
@login_required
def detail_view(request,pk):
    videos=models.Item.objects.get(pk=pk)
    commentform=CommentForm()
    if request.method =='POST':
        commentform=CommentForm(data=request.POST)
        if commentform.is_valid():
            comment=commentform.save(commit=False)
            comment.video=videos
            comment.user=request.user
            comment.save()
            messages.success(request,'You Have Commented Successfully')
            return HttpResponseRedirect(reverse('App_Video:details',kwargs={'pk':pk}))
    return render(request,'App_Video/FullVideo.html',context={'video':videos,'form':commentform})
    
    

templates/App_Login/Login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}  
{% block body_block %}
  
<div class="container my-5">

    <div class="main">
        <h1>Login</h1>
        <form method="POST">
            {% csrf_token %}
            <label for="firstname"> {{form.username.label}} :</label>&nbsp;&nbsp;
            {{form.username}}
            <label for="password"> {{form.password.label}} : </label>&nbsp;&nbsp;
            {{form.password}}
            <input type="submit" value="Login!" class="btn"><br>
        </form>
        <a href="{% url 'App_Login:signup' %}" class='mx-5 btn btn-dark'>Dont Have An Account? Sign Up</a>
    </div>

</div>


{% endblock body_block %}

templates/App_Login/changeProfile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container my-5">
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="Update" class='btn btn-warning my-4'>
    </form>
</div>



{% endblock body_block %}

templates/App_Login/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}  
{% block body_block %}
  

<div class="container my-5">

    <div class="main">
        <h1>Sign Up</h1>
        <form method="POST">
            {% csrf_token %}
            <label for="firstname"> {{form.username.label}} :</label>&nbsp;&nbsp;
            {{form.username}}
            <label for="email"> {{form.email.label}} :</label>&nbsp;&nbsp;
            {{form.email}}
            <label for="password"> {{form.password1.label}} : </label>&nbsp;&nbsp;
            {{form.password1}}
            <label for="cpassword"> {{form.password2.label}} :</label>&nbsp;&nbsp;&nbsp;
            {{form.password2}}
            <input type="submit" value="Sign Up!" class="btn"><br>
        </form>
        <a href="{% url 'App_Login:login' %}" class='mx-5 btn btn-dark'>Already Have An Account? Login</a>
    </div>

</div>



{% endblock body_block %}

templates/App_Video/FullVideo.html
{% extends "base.html" %}
{% load embed_video_tags %}
{% load crispy_forms_tags %}
{% block body_block %}


{% video video.video '100% x 480' query="rel=0&wmode=transparent" is_secure=True  %}
<h2 class='mx-5 my-2'> {{video.title}} </h2>
<div class="container my-5">
  <div class="row">
    <div class="col-md-6">
      <p>{{video.description|linebreaks}} </p>
    </div>
    <div class="col-md-6">
      <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <br>
        <button type="submit"  class="btn btn-info mb-3 w-100">Comment</button>
      </form>
      <ul class="list-group my-3">
        {% for comment in video.video_comment.all %}
        <li class="list-group-item d-flex justify-content-around">
          <b>{{comment.user}} =====> </b>
          <p>{{comment}}</p>
         <p> {{comment.commented_at|date:"D, d M,Y"}} </p>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>


{% endblock body_block %}

templates/App_Video/Home.html
{% extends "base.html" %}
{% load embed_video_tags %}

{% block body_block %}
<div class="container my-5">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for video in videos %}
        <div class="col">
            <a href="{% url 'App_Video:details' pk=video.pk %}" style="text-decoration: none;color:black;font-weight:bold" title="{{video.title}}">
                <div class="card">
                    {% video video.video as my_video %}
                    <img src="{{my_video.thumbnail}}" class="card-img-top" alt="">
                    {% endvideo %}
                    <div class="card-body">
                        <h5 class="card-title">{{video.title}}</h5>
                    </div>
                </div>
            </a>

        </div>
        {% endfor %}
    </div>

</div>


{% endblock body_block %}

templates/App_Video/comment.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body_block %}

<div class="container my-5">

 <form method="post">
{{form|crispy}}
</form> 
</div>


{% endblock body_block %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    {% load static %}  
    <link href="{% static 'form.css' %}" rel="stylesheet">    
    <title> Streaming Website </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'App_Video:home' %}">Streamer Platform</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'App_Video:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'App_Login:profile' %}">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'App_Login:logout' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'App_Video:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
              </li>
              {% endif %}
          </div>
        </div>
      </nav>
      {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %}  class="alert alert-dismissible fade show alert-{{message.tags}} {% endif %}" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">&times;</button>
      </div>
      {% endfor %}
      {% endif %}
          {% block body_block %}
            
          {% endblock body_block %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>